# Generated by Django 4.0.3 on 2022-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reply',
            field=models.TextField(default=None),
        ),
    ]
