# Generated by Django 4.0.3 on 2022-03-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_proposal_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
